"""empty message

Revision ID: 4fb8f388bd48
Revises: 715b747e0df8
Create Date: 2020-03-02 15:19:07.394114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fb8f388bd48'
down_revision = '715b747e0df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('asshole', table_name='users')
    op.drop_column('users', 'asshole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('asshole', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('asshole', 'users', ['asshole'], unique=True)
    # ### end Alembic commands ###
