"""empty message

Revision ID: 715b747e0df8
Revises: 
Create Date: 2020-03-02 15:17:41.256210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715b747e0df8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('asshole', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['asshole'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'asshole')
    # ### end Alembic commands ###
