"""empty message

Revision ID: 7a9ce4684e8b
Revises: 
Create Date: 2020-05-13 01:13:06.748280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9ce4684e8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('social_media_accounts', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_media_accounts')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'location')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
