"""empty message

Revision ID: 99f1e15d0f2f
Revises: ee4ae4f0e6d0
Create Date: 2020-05-25 19:55:09.101385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99f1e15d0f2f'
down_revision = 'ee4ae4f0e6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_link', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
