"""empty message

Revision ID: f52788db4114
Revises: 4f33239d3550
Create Date: 2020-06-05 13:37:28.500060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f52788db4114'
down_revision = '4f33239d3550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=120), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
